export enum NotificationType {
  COURSE_UNLOCKED = 'COURSE_UNLOCKED',
  SPECIAL_OFFER = 'SPECIAL_OFFER',
  PAYMENT_CONFIRMATION = 'PAYMENT_CONFIRMATION',
  COURSE_COMPLETED = 'COURSE_COMPLETED',
  NEW_LESSON = 'NEW_LESSON',
  REMINDER = 'REMINDER',
  APP_UPDATE = 'APP_UPDATE',
  SYSTEM = 'SYSTEM',
}
